"""init

Revision ID: 7e31850d3770
Revises: 
Create Date: 2025-07-05 18:29:54.842698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e31850d3770'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_unique_constraint('bonuses_id_key', 'bonuses', ['id'])
    op.create_unique_constraint('customers_telegram_id_key', 'customers', ['telegram_id'])
    op.alter_column('roles', 'role_id',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.create_unique_constraint('schedule_posts_schedule_id_key', 'schedule_posts', ['schedule_id'])
    op.alter_column('user_roles', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.create_unique_constraint('users_telegram_id_key', 'users', ['telegram_id'])

    roles_table = sa.table(
        'roles',
        sa.column('role_id', sa.SmallInteger),
        sa.column('name', sa.String)
    )
    op.bulk_insert(
        roles_table,
        [
            {'role_id': 1, 'name': 'waiter'},
            {'role_id': 2, 'name': 'manager'},
            {'role_id': 3, 'name': 'admin'},
            {'role_id': 4, 'name': 'owner'},
        ]
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_telegram_id_key', 'users', type_='unique')
    op.alter_column('user_roles', 'id',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint('schedule_posts_schedule_id_key', 'schedule_posts', type_='unique')
    op.alter_column('roles', 'role_id',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint('customers_telegram_id_key', 'customers', type_='unique')
    op.drop_constraint('bonuses_id_key', 'bonuses', type_='unique')
    # ### end Alembic commands ###
